### ISSUE TITLE
Respect decimal separator config and change the default to comma

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/SwagImportExport#1]
The config is not respected at the moment (always overridden [here](https://github.com/shopwareLabs/SwagImportExport/blob/c6d90ca7502c05265f3ea066bf18b3cc5fd598d4/Components/SwagImportExport/Transformers/SmartyExpressionEvaluator.php#L58-L72)), so we should:
1. Respect the decimal separator setting
2. Set the default to comma ("Yes"), to keep the current behavior

![33711198-6f393934-db43-11e7-9c95-84d7363ef6a6](https://user-images.githubusercontent.com/710188/33722502-728c0d7e-db6a-11e7-97fb-1f00fe354097.png)

This way the exports stay the same for current users (comma is needed for usable Microsoft Excel compatibility) but make the usable for UK users as well (by changing the config setting).

**Comment by windaishi** [comment]
You linked the wrong code part. The correct one: https://github.com/shopwareLabs/SwagImportExport/blob/c6d90ca7502c05265f3ea066bf18b3cc5fd598d4/Components/SwagImportExport/DbAdapters/ArticlesPricesDbAdapter.php#L131

**Comment by windaishi** [comment]
Opened a PR for this: https://github.com/shopwareLabs/SwagImportExport/pull/22

**Comment by samuelvogel** [comment]
As this is a Shopware PR we are going to wait for it's release via our [Google Doc Shopware PR list](https://docs.google.com/spreadsheets/d/1FXLjxFb528D2RCr1cg10SPJbWSmahuNCtgglrG1Uq2w/edit), I'm removing this from the board.
